package xyz.apollo30.skyblockremastered.items;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import xyz.apollo30.skyblockremastered.GUIs.GUIHelper;
import xyz.apollo30.skyblockremastered.SkyblockRemastered;
import xyz.apollo30.skyblockremastered.utils.Helper;
import xyz.apollo30.skyblockremastered.utils.Utils;

public class Accessories {

    private final SkyblockRemastered plugin;

    public Accessories(SkyblockRemastered plugin) {
        this.plugin = plugin;
    }

    public ItemStack FARMING_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("9af328c87b068509aca9834eface197705fe5d4f0871731b7b21cd99b9fddc")), "&fFarming Talisman", "&7Crit Damage: &c+1%", " ", "&7Increases your &f✦ Speed &7by ", "&a+10 &7while held in the ", "&bFarm&7, &bThe Barn&7, and ", "&bMushroom Desert&7.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack CROOKED_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Crooked Artifact", "&7Get 2% off most shops.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack SHADY_RING = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aShady Ring", "&7Get 1% off most shops.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack CAT_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aCat Talisman", "&7Speed: &a+1", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack LYNX_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Lynx Talisman", "&7Speed: &a+2", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack CHEETAH_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&5Cheetah Talisman", "&7Speed: &a+3", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack BAIT_RING = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Bait Ring", "&a5.0%&7 chance not to consume", "&7bait.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack GRAVITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("ba52632a9c8f7bde94719064234920ded48614e2bd8bc91afe7ffc2cd8a46f19")), "&aGravity Talisman", "&7Gives between &a+1&7 and &a+10&c", "&c❁ Strength&7 and &a❈ Defense", "&7the closer you are to the", "&7center of an Island!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack WOOD_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("219ad5215ba6c7e4e4d0668f02d3a9c937ac536acc75ac49e7bd7b1c8ccf80")), "&aWood Affinity Talisman", "&7Increases your &f✦ Speed&7 by ", "&a+10&7 while held in the ", "&bForest&7, &cGraveyard&7, and ", "&2Wilderness&7.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack SEA_CREATURE_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("eaa44b170d749ce4099aa78d98945d193651484089efb87ba88892c6fed2af31")), "&7Take &a5% &7less damage from Sea ", "&7Creatures.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack SCAVENGER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("211ab3a1132c9d1ef835ea81d972ed9b5cd8ddff0a07c55a749bcfcf8df5")), "&fScavenger Talisman", "&7Monsters drop coins when killed.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack VACCINE_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&fVaccine Talisman", "&7Provides immunity to &3Poison ", "&7damage when held.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack FROZEN_CHICKEN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Frozen Chicken", "&7Gives &a+1 & ✦ Speed &7when ", "&7held.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    // public ItemStack ORANGE_CRAB_HAT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&f&6Orange Crab of Celebration", "&7Magic Find: &a+1", " ", "&6Item Ability: Party Time &e&lPassive", "&7Gain &b+1✎ &7Intelligence while on your head for each SkyBlock year you've been playing.", " ", "&7Item Year: &e2020", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack CANDY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4eb46bbca3812363b59676ff629dc3698257fd178d394fadffda7143422e2f10")), "&5Candy Artifact", "&7Increases the drop chance of", "&7candies from mobs by &a15% ", "&7during the &6Spooky Festival.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack HASTE_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("3c26a1ec929d4b144266c56af11d9abaf93f6b274872c96d3e34cb7c7965")), "&9Haste Ring", "&r&7Gives &r&aHaste 1 &r&7for &r&a15 ", "&r&7seconds when breaking any block.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack FISH_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("46a27ec5ed3f01e301677f88fdbdd962c08368600907eec37a2d4dd8c7f835fc")), "&9Fish Affinity Talisman", "&a5.0% &r&7faster catch time.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack FARMER_ORB = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aFarmer Orb", "&7Increases the regrowth rate of", "&7nearby crops on the public", "&7islands, regrowing an extra crop", "&7every &a3&7 seconds.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack CAMPFIRE_GOD_BADGE = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6&6Campfire God Badge", "&7Heal &c44❤ &7per second", "&7while burning. ", "&7Also constantly heal &c2❤ &7per ", "&7second everywhere.", "", " &6Trial of Fire XXII", " &7\"Fire Guy!\"", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public ItemStack TALISMAN_OF_COINS = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&fTalisman of Coins", "&7Coins start appearing around you", "&7occasionally on public islands.", "&aLucky!", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack HEGEMONY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("313384a293cfbba3489b483ebc1de7584ca2726d7f5c3a620513474925e87b97")), "&6Hegemony Artifact", "&7Doubles the stats of the reforge ", "&7on this item.", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public ItemStack BITS_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("2ebadb1725aa85bb2810d0b73bf7cd74db3d9d8fc61c4cf9e543dbcc199187cc")), "&9Bits Talisman", "&7Whenever you gain bits, ", "&7grants a &b10% &7chance to", "&7gain double! ", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack BAT_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Bat Talisman", "&7Health: &a+1", "&7Speed: &a+1", "&7Intelligence: &a+1", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack BAT_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("93c8aa3fde295fa9f9c27f734bdbab11d33a2e43e855accd7465352377413b")), "&5Bat Ring", "&7Health: &a+3", "&7Speed: &a+2", "&7Intelligence: &a+2", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack POTION_AFFINITY_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&fPotion Affinity Talisman", "&7Increases the duration of any", "&7consumed potion by &a10%", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack POTION_AFFINITY_RING = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aPotion Affinity Ring", "&7Increases the duration of any", "&7consumed potion by &a25%", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack POTION_AFFINITY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("9f8b82427b260d0a61e6483fc3b2c35a585851e08a9a9df372548b4168cc817c")), "&9Potion Affinity Artifact", "&7Increases the duration of any", "&7consumed potion by &a50%", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack EXPERIENCE_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.ENCHANTED_BOOK), "&5&5Experience Artifact", "&7Increase the enchanting experience", "&7you gain by &a25%&7 while", "&7this item is in your inventory.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack WOLF_RING = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9&9Wolf Ring", "&7Reduces the damage taken", "from wolves by &a10%&7.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack WOLF_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&fWolf Talisman", "&7Reduces the damage taken", "from wolves by &a5%&7.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack SPEED_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("8624bacb5f1986e6477abce4ae7dca1820a5260b6233b55ba1d9ba936c84b")), "&9Speed Artifact", "&7Gives &a+5 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack SPEED_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("c2da40a91f8fa7e1cbdd934da92a7668dc95d75b57c9c80a381c5e178cee6ba7")), "&aSpeed Ring", "&7Gives &a+3 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack SPEED_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("f06706eecb2d558ace27abda0b0b7b801d36d17dd7a890a9520dbe522374f8a6")), "&fSpeed Talisman", "&7Gives &a+1 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack NIGHT_CRYSTAL = GUIHelper.addLore(new ItemStack(Material.NETHER_STAR), "&9Night Crystal", "&7Increases your &c❁ Strength", "&7and &a❈ Defense &7by &a+5", "&7during the night.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack MAGNETIC_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aMagnetic Talisman", "&7Increase the item pickup range ", "&7by &a3x&7.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack SEAL_OF_THE_FAMILY = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&5Seal of the Family", "&7Get 3% off on most shops.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack MELODYS_HAIR = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.STRING)), "&5♪ Melody's Hair ♫", "&7Intelligence: &a+6", " ", "&7A single strand of hair from Melody's head.", " ", "&7Left-Click: &eTune Up!", "&7Right-Click: &dPlay Note!", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack SEA_CREATURE_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Sea Creature Artifact", "&7Take &a15.0%&7 less damage from ", "&7Sea Creatures.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack PIGS_FOOT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Pig's Foot", "&7Speed: &a+1", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack DAY_CRYSTAL = GUIHelper.addLore(new ItemStack(Material.NETHER_STAR), "&9Day Crystal", "&7Increases your &c❁ Strength", "&7and &a❈ Defense &7by &a+5", "&7during the day.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack SPIDER_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aSpider Talisman", "&7Reduces Spider, Cave Spider", "&7and Silverfish damage by 5%", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack INTIMIDATION_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&9Intimidation Artifact", "&7Monsters at or below Level &a25 ", "&7will no longer target you.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public ItemStack INTIMIDATION_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("f931ca9e46fcf351354fa022992fa07cc59be50ffb80e9dd8af4973378cf89d5")), "&aIntimidation Ring", "&7Monsters at or below Level &a5 ", "&7will no longer target you.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public ItemStack SPIDER_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("8300986ed0a04ea79904f6ae53f49ed3a0ff5b1df62bba622ecbd3777f156df8")), "&5Spider Artifact", "&7Reduces damage taken from", "&7Spiders and Cave Spiders", "&7by &a15%&7.", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Spider Slayer 7", "&5&lEPIC ACCESSORY");
    public ItemStack TARANTULA_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&5Tarantula Talisman", "&7Every &a10th&7 melee hit on the", "&7same enemy deals &c+10%&7", "&cdamage", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public ItemStack INTIMIDATION_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&fIntimidation Talisman", "&7Level &a1 &7monsters will no ", "&7longer target you.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public ItemStack BAT_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("382fc3f71b41769376a9e92fe3adbaac3772b999b219c9d6b4680ba9983e527")), "&6Bat Artifact", "&7Health: &a+5", "&7Speed: &a+3", "&7Intelligence: &a+3", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public ItemStack HUNTER_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("317b51e086f201448a4b45b0b91e97faf4d1739071480be6d5cab0a054512164")), "&9Hunter Ring", "&7Gain &b+5% &7Combat XP from", "&7monster kills.", " ", "&4☠ &cRequires &5Wolf Slayer 7", "&9&lRARE ACCESSORY");
    public ItemStack HUNTER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("317b51e086f201448a4b45b0b91e97faf4d1739071480be6d5cab0a054512164")), "&aHunter Talisman", "&7Gain &b+2% &7Combat XP from", "&7monster kills.", " ", "&4☠ &cRequires &5Wolf Slayer 7", "&a&lUNCOMMON ACCESSORY");
    public ItemStack RED_CLAW_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&5Red Claw Artifact", "&7Crit Damage: &c+5%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 5", "&5&lEPIC ACCESSORY");
    public ItemStack RED_CLAW_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("59d9b327ff82f6e109b8746c48bfb7f641e1552855493dd4118be24d5b02bc0a")), "&9Red Claw Ring", "&7Crit Damage: &c+3%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 5", "&9&lRARE ACCESSORY");
    public ItemStack RED_CLAW_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 3), "&aRed Claw Talisman", "&7Crit Damage: &c+1%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 1", "&a&lUNCOMMON ACCESSORY");
}