package xyz.apollo30.skyblockremastered.items;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import xyz.apollo30.skyblockremastered.guis.GUIHelper;
import xyz.apollo30.skyblockremastered.utils.Helper;
import xyz.apollo30.skyblockremastered.utils.Utils;
import xyz.apollo30.skyblockremastered.SkyblockRemastered;

public class Accessories {

    private final SkyblockRemastered plugin;

    public Accessories(SkyblockRemastered plugin) {
        this.plugin = plugin;
    }

    // Collections
    public static ItemStack FARMING_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWFmMzI4Yzg3YjA2ODUwOWFjYTk4MzRlZmFjZTE5NzcwNWZlNWQ0ZjA4NzE3MzFiN2IyMWNkOTliOWZkZGMifX19"), "&fFarming Talisman", "&7Crit Damage: &c+1%", " ", "&7Increases your &f✦ Speed &7by ", "&a+10 &7while held in the ", "&bFarm&7, &bThe Barn&7, and ", "&bMushroom Desert&7.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack VACCINE_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzE0MDhlZGU4YjRmNDQ0MDE1YzU5YWJkNWNkMzJiODc2OWRlNTE4ODFlZGFiY2MxNWFiYjY1MTlmNWI0OSJ9fX0="), "&fVaccine Talisman", "&7Provides immunity to &2Poison ", "&7damage when held.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack FARMER_ORB = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzNiMTcyYTk3OWVmZjliZjViZmI4MGViODUxNWQ5M2U0ODg4Y2M0MWNkODA2NDczZjJhOWEwZDhiZDI5ZTMifX19"), "&aFarmer Orb", "&7Increases the regrowth rate of", "&7nearby crops on the public", "&7islands, regrowing an extra crop", "&7every &a3&7 seconds.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack NIGHT_VISION_CHARM = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWMzM2ZhMTQ4N2VjODM3NmQ4YzhmNGJkOTEwNzdkYWRlY2MyYWQxYmNlM2I3ZDQ4ZmI4ODIxOGZiZmM2ZmUxOSJ9fX0="), "&fNight Vision Charm", "&7Grants Night Vision I while this", "&7item is in your inventory.", " ", "&8This item can be reforged!", "&c&lCOMMON");
    public static ItemStack SPEED_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("ewogICJ0aW1lc3RhbXAiIDogMTU5MDA4OTk4MjM0MiwKICAicHJvZmlsZUlkIiA6ICJjOTU4YTRiMWY4OGU0ZGVjOTI3NGVlMGQ3Nzg2ZGFkYSIsCiAgInByb2ZpbGVOYW1lIiA6ICJBbHNvRGN0ciIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9mMDY3MDZlZWNiMmQ1NThhY2UyN2FiZGEwYjBiN2I4MDFkMzZkMTdkZDdhODkwYTk1MjBkYmU1MjIzNzRmOGE2IgogICAgfQogIH0KfQ=="), "&9Speed Artifact", "&7Gives &a+5 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack SPEED_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("c2da40a91f8fa7e1cbdd934da92a7668dc95d75b57c9c80a381c5e178cee6ba7")), "&aSpeed Ring", "&7Gives &a+3 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack SPEED_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("f06706eecb2d558ace27abda0b0b7b801d36d17dd7a890a9520dbe522374f8a6")), "&fSpeed Talisman", "&7Gives &a+1 &f✦ Speed &7when held.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack FEATHER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&fFeather Talisman", "&fUnique Effect: Light Weight", " &7Increase how high you can fall", "&7before taking fall damage by", "&a5&7 blocks.", " ", "&7This Talisman doesn't work if ", "&7the &bFeather Ring &7or &bFeather", "&bArtifact&7 is in your inventory!", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack FEATHER_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aFeather Ring", "&fUnique Effect: Light Weight", "&7Increase how high you can fall", "&7before taking fall damage by", "&a7&7 blocks, and reduces fall", "&7damage by &a5.0%&7.", " ", "&7This Ring doesn't work if the", "&bFeather Artifact&7 is in your ", "&7inventory!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack FEATHER_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjE2NGNjNzYwODE1OTlhMjBhNjg5NmEzODE4MzIyYTBjZGMwODA2OWZmOTYwYmJkNzlmZjU0ZmM0NWUzNWVlNiJ9fX0="), "&9Feather Artifact", "&bUnique Effect: Light Weight", "&7Increases how high you can fall", "&7before taking fall damage by", "&a10 &7blocks, and reduces fall", "&7damage by &a15.0%&7.", " ", "&8This item can be reforged!", "&9&lRARE");
    public static ItemStack PIGGY_BANK = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk4ZGY0MmY0NzdmMjEzZmY1ZTlkN2ZhNWE0Y2M0YTY5ZjIwZDljZWYyYjkwYzRhZTRmMjliZDE3Mjg3YjUifX19"), "&aPiggy Bank", "&7Saves your coins from death.", "&7Only when in player inventory.", "&cFragile!", " ", "&8Triggers when losing 20k+ coins.", " ", "&8This item can be reforged!", "&a&lUNCOMMON");
    public static ItemStack CRACKED_PIGGY_BANK = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&a&cCracked Piggy Bank", "&7Saves &c75%&7 of your coins on death. ", "&7Only when in player inventory.", "&cVery fDragile!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack BROKEN_PIGGY_BANK = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&a&7Broken Piggy Bank", "&7It broke!", " ", "&aRight-click to view recipes!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack POTION_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("3a943baf71458596aff4eba879f8ac5d2ba267c98385e67673f48ebea5fa")), "&fPotion Affinity Talisman", "&7Increases the duration of any", "&7consumed potion by &a10%", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack POTION_AFFINITY_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("9f8b82427b260d0a61e6483fc3b2c35a585851e08a9a9df372548b4168cc817c")), "&aPotion Affinity Ring", "&7Increases the duration of any", "&7consumed potion by &a25%", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack POTION_AFFINITY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzcyNDY2NjAzYmFlOTA2M2NlN2Q5NDM1MTEwMzQ2OWJlY2EzYzVmZTJiMWU5NzdlNjQyN2RlZjM3Njk5ZWM5In19fQ=="), "&9Potion Affinity Artifact", "&7Increases the duration of any", "&7consumed potion by &a50%", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack HASTE_RING = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2MyNmExZWM5MjlkNGIxNDQyNjZjNTZhZjExZDlhYmFmOTNmNmIyNzQ4NzJjOTZkM2UzNGNiN2M3OTY1In19fQ=="), "&9Haste Ring", "&r&7Gives &r&aHaste 1 &r&7for &r&a15 ", "&r&7seconds when breaking any block.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack EXPERIENCE_ARTIFACT = GUIHelper.addLore(new ItemStack(Material.ENCHANTED_BOOK), "&5&5Experience Artifact", "&7Increase the enchanting experience", "&7you gain by &a25%&7 while", "&7this item is in your inventory.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack TALISMAN_OF_COINS = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("452dca68c8f8af533fb737faeeacbe717b968767fc18824dc2d37ac789fc77")), "&fTalisman of Coins", "&7Coins start appearing around you", "&7occasionally on public static islands.", "&aLucky!", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack MAGNETIC_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI5YzQ5ZmZkZjRjZTRjNmY1ZjA0OWVmYzhjYTBlMDhiOWI1YmJmM2M2YTg3ODNkZmFhY2NhZDc3ZGZjOTk3YSJ9fX0="), "&aMagnetic Talisman", "&7Increase the item pickup range ", "&7by &a3x&7.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack NIGHT_CRYSTAL = GUIHelper.addLore(new ItemStack(Material.NETHER_STAR), "&9Night Crystal", "&7Increases your &c❁ Strength", "&7and &a❈ Defense &7by &a+5", "&7during the night.", " ", "&8This item can be reforged!", " ", "&9&lRARE ACCESSORY");
    public static ItemStack DAY_CRYSTAL = GUIHelper.addLore(new ItemStack(Material.NETHER_STAR), "&9Day Crystal", "&7Increases your &c❁ Strength", "&7and &a❈ Defense &7by &a+5", "&7during the day.", " ", "&8This item can be reforged!", " ", "&9&lRARE ACCESSORY");
    public static ItemStack GRAVITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmE1MjYzMmE5YzhmN2JkZTk0NzE5MDY0MjM0OTIwZGVkNDg2MTRlMmJkOGJjOTFhZmU3ZmZjMmNkOGE0NmYxOSJ9fX0="), "&aGravity Talisman", "&7Gives between &a+1&7 and &a+10&c", "&c❁ Strength&7 and &a❈ Defense", "&7the closer you are to the", "&7center of an Island!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack FIRE_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzBhNDRkNTFlY2M3OWY2OTRjZmQ2MDIyOGM4ODQyODg0OGNhNjE4ZTM2YTY1OWE0MTZlOTI0NmQ4NDFhZWM4In19fQ=="), "&fFire Talisman", "&7Provides immunity to &aFire", "&7while held in the inventory", " ", "&8This item can be reforged!", "&a&fCOMMON ACCESSORY");
    public static ItemStack LAVA_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzA3OGYzZjI0YjE3NjBmOWQ0YWJiMDg1MWViOGY2YzdkZmZmODg1NTcwOGU2MDQ5ZDE1ZGMwMjA0MmJhODQzNiJ9fX0="), "&aLava Talisman", "&7Provides immunity to &aLava", "&7while held in the inventory", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack WOOD_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjE5YWQ1MjE1YmE2YzdlNGU0ZDA2NjhmMDJkM2E5YzkzN2FjNTM2YWNjNzVhYzQ5ZTdiZDdiMWM4Y2NmODAifX19"), "&aWood Affinity Talisman", "&7Increases your &f✦ Speed&7 by ", "&a+10&7 while held in the ", "&bForest&7, &cGraveyard&7, and ", "&2Wilderness&7.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack HEALING_RING = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzg3OWZlNzU0M2NhMWQ1ODU1ZTk2MTUxNGNmZjdlMjcyOGQyNzQwY2EzYzMzMzIwZDg0ZGQwNTNhZWE1ZGNiN2QifX19"), "&aHealing Ring", "&7Increases healing by &a10.0%", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack BAIT_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("5a316d585b789b582f2d99e8e6cb2d70433e8996fab024a74bc790e22aedcdeb")), "&9Bait Ring", "&a5.0%&7 chance not to consume", "&7bait.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack SEA_CREATURE_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("eaa44b170d749ce4099aa78d98945d193651484089efb87ba88892c6fed2af31")), "&7Take &a5% &7less damage from Sea ", "&7Creatures.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack SEA_CREATURE_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aSea Creature Ring", "&7Take &a10.0% &7less damage from", "&7Sea Creatures.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack SEA_CREATURE_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzcwYTAxMDc5MWNiMWM4OTAyYzYyMjMyMDdhYTQ0ZmU5ZDFmODRmM2JjOGZmYjFiNGNjM2NmNTU3M2UwNTZlNzEifX19"), "&9Sea Creature Artifact", "&7Take &a15.0%&7 less damage from ", "&7Sea Creatures.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack PERSONAL_COMPACTOR_4000 = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.DROPPER)), "&aPersonal Compactor 4000", "&7Automatically turns certain", "&7materials in your inventory into", "&7their enchanted form.", " ", "&aRight-click to configure!", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack PERSONAL_COMPACTOR_5000 = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.DROPPER)), "&9Personal Compactor 5000", "&7Automatically turns certain", "&7materials in your inventory into", "&7their enchanted form.", " ", "&aRight-click to configure!", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack PERSONAL_COMPACTOR_6000 = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.DROPPER)), "&5Personal Compactor 6000", "&7Automatically turns certain", "&7materials in your inventory into", "&7their enchanted form.", " ", "&aRight-click to configure!", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");

    // Obtained from NPC SHOP
    public static ItemStack ZOMBIE_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 2), "&fZombie Talisman", "&7Reduce the damage taken from", "&7Zombies by &a5%", " ", "&f&lCOMMON");
    public static ItemStack SKELETON_TALISMAN = GUIHelper.addLore(new ItemStack(Material.SKULL_ITEM, 1, (byte) 1), "&fSkeleton Talisman", "&7Reduce the damage taken from", "&7Skeletons by &a5%", " ", "&f&lCOMMON");
    public static ItemStack VILLAGE_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&fVillage Affinity Talisman", "&7Increases your &f" + GUIHelper.getUnicode("speed") + " Speed &7by", "&a+10 &7while held in the", "&bVillage&7.", " ", "&f&lCOMMON");
    public static ItemStack MINE_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&fMine Affinity Talisman", "&7Increases your &f" + GUIHelper.getUnicode("speed") + " Speed &7by", "&a+10 &7while held in the &bCoal", "&bMine&7, &6Gold Mine&7, &bDeep", "&bCaverns&7, &bGunpowder Mines&7,", "&bLapis Quarry&7, &bPigmen's", "&bDen&7, &bSlimehill&7, &bDiamond", "&bReserve&7, and &bObsidian", "&dSanctuary&7.", " ", "&f&lCOMMON ACCESSORY");
    public static ItemStack INTIMIDATION_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("f931ca9e46fcf351354fa022992fa07cc59be50ffb80e9dd8af4973378cf89d5")), "&fIntimidation Talisman", "&7Level &a1 &7monsters will no ", "&7longer target you.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack INTIMIDATION_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("72a7dcbf7eca6b6f6386591d237991ca1b888a4f0c753ff9a3202cf0e92229e3")), "&aIntimidation Ring", "&7Monsters at or below Level &a5 ", "&7will no longer target you.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack INTIMIDATION_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjkzMWNhOWU0NmZjZjM1MTM1NGZhMDIyOTkyZmEwN2NjNTliZTUwZmZiODBlOWRkOGFmNDk3MzM3OGNmODlkNSJ9fX0="), "&9Intimidation Artifact", "&7Monsters at or below Level &a25 ", "&7will no longer target you.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack SCAVENGER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjExYWIzYTExMzJjOWQxZWY4MzVlYTgxZDk3MmVkOWI1Y2Q4ZGRmZjBhMDdjNTVhNzQ5YmNmY2Y4ZGY1In19fQ=="), "&fScavenger Talisman", "&7Monsters drop coins when killed.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack BITS_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("2ebadb1725aa85bb2810d0b73bf7cd74db3d9d8fc61c4cf9e543dbcc199187cc")), "&9Bits Talisman", "&7Whenever you gain bits, ", "&7grants a &b10% &7chance to", "&7gain double! ", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");

    // Event Reward
    public static ItemStack NEW_YEAR_CAKE_BAG = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTQ1NzNkNjU0NmJhNzFlZmYzYjY3ZTUxMTZiMGQ3NWUyOWFkZjY3MTM1ZTk1MzM4ZGNhODNlZWMyODhmMjcifX19")), "&aNew Year Cake Bag", "&7Holds &dNew Year Cake&7. Each", "&7unique New Year Cake within this", "&7bag grants &a+1 &c" + GUIHelper.getUnicode("heart") + " Health&7.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack BAT_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("93c8aa3fde295fa9f9c27f734bdbab11d33a2e43e855accd7465352377413b")), "&5Bat Ring", "&7Health: &a+3", "&7Speed: &a+2", "&7Intelligence: &a+2", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack BAT_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzgyZmMzZjcxYjQxNzY5Mzc2YTllOTJmZTNhZGJhYWMzNzcyYjk5OWIyMTljOWQ2YjQ2ODBiYTk5ODNlNTI3In19fQ=="), "&6Bat Artifact", "&7Health: &a+5", "&7Speed: &a+3", "&7Intelligence: &a+3", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CANDY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aCandy Talisman", "&7Increases the chance for mobs to", "&7drop Candy by &a5%&7 during the", "&6Spooky Festival.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CANDY_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Candy Ring", "&7Increases the chance for mobs to", "&7drop Candy by &a10%&7 during the", "&6Spooky Festival.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CANDY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGViNDZiYmNhMzgxMjM2M2I1OTY3NmZmNjI5ZGMzNjk4MjU3ZmQxNzhkMzk0ZmFkZmZkYTcxNDM0MjJlMmYxMCJ9fX0="), "&5Candy Artifact", "&7Increases the drop chance of", "&7candies from mobs by &a15% ", "&7during the &6Spooky Festival.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CANDY_RELIC = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&6Candy Relic", "&7Increases the drop chance of", "&7candies from mobs by &a20%&7", "&7during the &6Spooky", "&6Festival.", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack POTATO_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("ewogICJ0aW1lc3RhbXAiIDogMTU5MjUzMTI1MDg3MCwKICAicHJvZmlsZUlkIiA6ICI4MmEyZDY5OTMwOTM0NjkxOGE3NDc4ZTI2YWEyMGJmMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJMY3V0ZSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8zMTg0NzZlM2NmMGQ1ZmM4YWIxNzYxMDY1Y2YwZTM3MmIxMTAwNGVkNGM5NzE1NjM5NmUxN2M4NjliNGFhMzg5IgogICAgfQogIH0KfQ=="), "&fPotato Talisman", "&7Your potato minions farm &a5%", "&7faster while wearing on your", "&7island.", " ", "&8Forged by the Potato King", "&7after winning the Great", "&7Potato War.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    // BEASTMASTER CREST
    // MINERAL TALISMAN

    // CRAB HAT ACCESSORIES
    public static ItemStack GREEN_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("98d99983ab5986921251a29bba96c8e734f5de084a296cb627bcd64fd0fba593")), "&2Green Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack AQUA_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("2e1556958b1df4fd6228c9dcbd8c053f5d8902a41c4a59376bd0df1c60be8369")), "&bAqua Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack BLACK_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("cb85828267e59e83edc3bef235102e43fb70922622ccc3809a326a8c5632199a")), "&0Black Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack LIME_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("993c60fd0dd130695e378eef010a7d3c5dfde77f6b82b20b8124cfb830017ff")), "&aLime Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack RED_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("56b61f826dd6bfc1e3191a8369aeb0435c5a5335563431a538585ad039da1e0c")), "&cRed Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack ORANGE_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("ae38a15704089676a24e9eeccf4c290644d352c7d8f2b4135fa3538625107db")), "&6Orange Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack YELLOW_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("6b92684647051bd27ee04adb4098ee9bccca45a726a7cbf38e98b7e75cb889f4")), "&eYellow Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack PURPLE_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("2e3af5824014b57f4a4a84d4bb7fb88cac9e4ac75d00c7adb09dfe5ab737e224")), "&5Purple Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack PINK_CRAB_HAT_OF_CELEBRATION = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("effaf0dc89da58bd1ed08f917407853e58d7bcbf5e6b5f33586389eb863a5bbd")), "&dPink Crab Hat Of Celebration", "&7Magic Find: &a+1", " ", "&7Item year: &e2020", " ", "&6Item Ability: Party Time! &e&lPassive", "&7Gain &b+1✎ Intelligence &7while", "&7on your head for each SkyBlock", "&7year you've been playing.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");

    // Mob Drops
    public static ItemStack BAT_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("9e99deef919db66ac2bd28d6302756ccd57c7f8b12b9dca8f41c3e0a04ac1cc")), "&9Bat Talisman", "&7Health: &a+1", "&7Speed: &a+1", "&7Intelligence: &a+1", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack SPIDER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQ3ZTNiMTlhYzRmM2RlZTljNTY3N2MxMzUzMzNiOWQzNWE3ZjU2OGI2M2QxZWY0YWRhNGIwNjhiNWEyNSJ9fX0="), "&aSpider Talisman", "&7Reduces Spider, Cave Spider", "&7and Silverfish damage by 5%", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack FISH_AFFINITY_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZhMjdlYzVlZDNmMDFlMzAxNjc3Zjg4ZmRiZGQ5NjJjMDgzNjg2MDA5MDdlZWMzN2EyZDRkZDhjN2Y4MzVmYyJ9fX0="), "&9Fish Affinity Talisman", "&a5.0% &r&7faster catch time.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack WOLF_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("69d1d3113ec43ac2961dd59f28175fb4718873c6c448dfca8722317d67")), "&fWolf Talisman", "&7Reduces the damage taken", "&7from wolves by &a5%&7.", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack TARANTULA_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("442cf8ce487b78fa203d56cf01491434b4c33e5d236802c6d69146a51435b03d")), "&5Tarantula Talisman", "&7Every &a10th&7 melee hit on the", "&7same enemy deals &c+10%&7", "&cdamage", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");

    // Slayer Recipes
    // ZOMBIE RING
    public static ItemStack DEVOUR_RING = GUIHelper.addLore(GUIHelper.addSkull("eyJ0aW1lc3RhbXAiOjE1NjgzNDkwODM1MTksInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhhN2QxYTUyZThjOGRkYWFmMGM0MjhlMWZlNDkwMWVmMzNlZmYyNTFmMjg5ZGUyNzE2Mzk1Y2FkMjBiZjMwOWIifX19"), "&9Devour Ring", "&7Heal &c5." + GUIHelper.getUnicode("heart") + " &7when killing a", "&7monster.", "&8Cooldown: &a0.5s", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Zombie Slayer 5", "&9&lRARE ACCESSORY");
    // ZOMBIE ARTIFACTS
    public static ItemStack SPIDER_RING = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzY1MmJkNzYxN2U1NmM3NTY1MTRmODNjMjhkZDFkOTZhN2U1ZTE2N2JmN2ZiNTkzNjkzZmM2NTA0NmY3OTkifX19"), "&9Spider Ring", "&7Reduces the damage taken from", "&7Spiders and Cave Spiders", "&7by &a10%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Zombie Slayer 5", "&9&lRARE ACCESSORY");
    public static ItemStack SPIDER_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("8300986ed0a04ea79904f6ae53f49ed3a0ff5b1df62bba622ecbd3777f156df8")), "&5Spider Artifact", "&7Reduces damage taken from", "&7Spiders and Cave Spiders", "&7by &a15%&7.", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Spider Slayer 7", "&5&lEPIC ACCESSORY");
    // SURVIVOR CUBE
    public static ItemStack RED_CLAW_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0aW1lc3RhbXAiOjE1NzA1NDk5NDY3MTIsInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzMxN2I1MWUwODZmMjAxNDQ4YTRiNDViMGI5MWU5N2ZhZjRkMTczOTA3MTQ4MGJlNmQ1Y2FiMGEwNTQ1MTIxNjQifX19"), "&aRed Claw Talisman", "&7Crit Damage: &c+1%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 1", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack RED_CLAW_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("59d9b327ff82f6e109b8746c48bfb7f641e1552855493dd4118be24d5b02bc0a")), "&9Red Claw Ring", "&7Crit Damage: &c+3%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 5", "&9&lRARE ACCESSORY");
    public static ItemStack RED_CLAW_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("caf59b8aa0f83546ef0d178ccf87e7ed88cf7858caae79b3633cbd75b650525f")), "&5Red Claw Artifact", "&7Crit Damage: &c+5%", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 5", "&5&lEPIC ACCESSORY");
    public static ItemStack HUNTER_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("317b51e086f201448a4b45b0b91e97faf4d1739071480be6d5cab0a054512164")), "&aHunter Talisman", "&7Gain &b+2% &7Combat XP from", "&7monster kills.", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 7", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack HUNTER_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("317b51e086f201448a4b45b0b91e97faf4d1739071480be6d5cab0a054512164")), "&9Hunter Ring", "&7Gain &b+5% &7Combat XP from", "&7monster kills.", " ", "&8This item can be reforged!", "&4☠ &cRequires &5Wolf Slayer 7", "&9&lRARE ACCESSORY");

    // Quest Trials
    public static ItemStack PIGS_FOOT = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHBzOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYwNGZhZWJlZmQwYThmNzIxNDAzZTMxNDJlZmVjYjgzZmJmNGI3ZDFmNzA1ZDBjOWI0NGQ5MWYwYmY0MDEyN2IifX19"), "&9Pig's Foot", "&7Speed: &a+1", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack WOLF_PAW = GUIHelper.addLore(GUIHelper.addSkull("eyJ0aW1lc3RhbXAiOjE1NzE4NTc5NTYyNjksInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzdhZmQyMjcwNGVlYjVjNjdiZTY0OWRkZmUxZGEwYzY1ODE1OGE3MDU4ZDAxNzM5ZGUzMWM5NGY2Yjk4MDg4NjkifX19"), "&aWolf Paw", "&7Speed: &a+1", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack MELODYS_HAIR = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.STRING)), "&5♪ Melody's Hair ♫", "&7Intelligence: &a+6", " ", "&7A single strand of hair from Melody's head.", " ", "&7Left-Click: &eTune Up!", "&7Right-Click: &dPlay Note!", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack SHADY_RING = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("da8524274a65d8a80a0f44e103e2021e27c8916e965aa11f665ac0c49be40ec6")), "&aShady Ring", "&7Get 1% off most shops.", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CROOKED_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("70a010791cb1c8902c6223207aa44fe9d1f84f3bc8ffb1b4cc3cf5573e056e71")), "&9Crooked Artifact", "&7Get 2% off most shops.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack SEAL_OF_THE_FAMILY = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("7ab83858ebc8ee85c3e54ab13aabfcc1ef2ad446d6a900e471c3f33b78906a5b")), "&5Seal of the Family", "&7Get 3% off on most shops.", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack FROZEN_CHICKEN = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDYxYzMzMDI0MjQ2ZWQyMTlhMTMxN2UyNDU5MTMwZjJhZWQyMjc2NTVlODVjZjAxZmM1MTM0ODEyMzZkOGRkMSJ9fX0="), "&9Frozen Chicken", "&7Gives &a+1 & ✦ Speed &7when ", "&7held.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAT_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("e4b45cbaa19fe3d68c856cd3846c03b5f59de81a480eec921ab4fa3cd81317")), "&aCat Talisman", "&7Speed: &a+1", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack LYNX_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("e4b45cbaa19fe3d68c856cd3846c03b5f59de81a480eec921ab4fa3cd81317")), "&9Lynx Talisman", "&7Speed: &a+2", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CHEETAH_TALISMAN = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("1553f8856dd46de7e05d46f5fc2fb58eafba6829b11b160a1545622e89caaa33")), "&5Cheetah Talisman", "&7Speed: &a+3", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");

    // Progressive Accessories
    public static ItemStack CAMPFIRE_BADGE_2 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("af41cc2250d2f5cfcf4384aa0cf3e23c19767549a2a8abd7532bd52c5a1de")), "&fCampfire Initiate Badge", "&7Heal &c4:heart: &7per second ", "&7while burning. ", " ", "&6Trial of fire II", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_3 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("af41cc2250d2f5cfcf4384aa0cf3e23c19767549a2a8abd7532bd52c5a1de")), "&fCampfire Initiate Badge", "&7Heal &c6:heart: &7per second ", "&7while burning. ", " ", "&6Trial of fire III", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_4 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("af41cc2250d2f5cfcf4384aa0cf3e23c19767549a2a8abd7532bd52c5a1de")), "&fCampfire Initiate Badge", "&7Heal &c8:heart: &7per second ", "&7while burning. ", " ", "&6Trial of fire IV", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_5 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aCampfire Adept Badge", "&7Heal &c10:heart: &7per second ", "&7while burning. ", " ", "&6Trial of fire V", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_6 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aCampfire Adept Badge", "&7Heal &c12❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire VI", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_7 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aCampfire Adept Badge", "&7Heal &c14❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire VII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_8 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&aCampfire Adept Badge", "&7Heal &c16❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire VIII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&a&lUNCOMMON ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_9 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Campfire Cultist Badge", "&7Heal &c18❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire IX", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_10 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Campfire Cultist Badge", "&7Heal &c20❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire X", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_11 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Campfire Cultist Badge", "&7Heal &c22❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XI", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_12 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Campfire Cultist Badge", "&7Heal &c24❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_13 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&9Campfire Cultist Badge", "&7Heal &c26❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XIII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_14 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c28❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XIV", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_15 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c30❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XV", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_16 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c32❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XVI", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_17 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c34❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XVII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_18 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c36❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XVIII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_19 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c38❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XIX", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_20 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c40❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XX", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_21 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&5Campfire Scion Badge", "&7Heal &c42❤ &7per second ", "&7while burning. ", " ", "&6Trial of fire XXI", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_22 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c44❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c2❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_23 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c46❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c3❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXIII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_24 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c48❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c4❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXIV", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_25 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c50❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c5❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXV", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_26 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c52❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c6❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXVI", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_27 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c54❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c7❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXVII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_28 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c56❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c8❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXVIII", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_29 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c58❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c9❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXIX", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack CAMPFIRE_BADGE_30 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("4080bbefca87dc0f36536b6508425cfc4b95ba6e8f5e6a46ff9e9cb488a9ed")), "&6Campfire God Badge", "&7Heal &c60❤ &7per second ", "&7while burning. ", "&7Also constantly heal &c10❤ &7per", "&7second everywhere.", "", "&6Trial of fire XXX", "&8&o\"Fire guy!\"", " ", "&8This item can be reforged!", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");

    public static ItemStack SHINY_YELLOW_ROCK = GUIHelper.addLore(Helper.addEnchantGlow(new ItemStack(Material.GOLD_NUGGET)), "&fShiny Yellow Rock", "&7Grants a 1 in", "&71,000,000,000,000 chance to", "&7deal §c+100% §7damage.", " ", "&8True love is tough to find,", "&8but finding it hits you hard!", " ", "&7Requires quest progress!", " ", "&8This item can be reforged!", "&f&lCOMMON ACCESSORY");
    // YELLOW ROCK OF LOVE
    // MEDIOCRE RING OF LOVE
    // RUBBISH RING OF LOVE
    // MODEST RING OF LOVE
    // REFINED RING OF LOVE
    // CLASSY RING OF LOVE
    public static ItemStack WEDDING_RING_7 = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("eyJ0aW1lc3RhbXAiOjE1NzMwNjU2NzkyMDMsInByb2ZpbGVJZCI6IjQxZDNhYmMyZDc0OTQwMGM5MDkwZDU0MzRkMDM4MzFiIiwicHJvZmlsZU5hbWUiOiJNZWdha2xvb24iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhmYjI2NWM4Y2M2MTM2MDYzYjRlYjE1NDUwZmUxZmUxYWI3NzM4YjBiZjU0ZDI2NTQ5MGUxZWY0OWRhNjBiN2MifX19")), "&5Exquisite Ring of Love", "&7Grants a 1 in 10,000 chance to", "&7deal &c+100& &7damage", " ", "&8True love is tough to find,", "&8but finding it hits you hard!", " ", "&7Requires quest progress!", " ", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");
    // INVALUABLE RING OF LOVE
    // LEGENDARY RING OF LOVE

    // Other
    public static ItemStack WOLF_RING = GUIHelper.addLore(GUIHelper.addSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjgzYTJhYTlkMzczNGI5MTlhYzI0Yzk2NTllNWUwZjg2ZWNhZmJmNjRkNDc4OGNmYTQzM2JiZWMxODllOCJ9fX0="), "&9&9Wolf Ring", "&7Reduces the damage taken", "&7from wolves by &a10%&7.", " ", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack ENDER_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("969da4e7b8d558af02e80e2e1669ceb6084898db55907ef3e66d9a329329e941")), "&6Hegemony Artifact", "&7Doubles the stats of the reforge ", "&7on this item.", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack WITHER_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("964e1c3e315c8d8fffc37985b6681c5bd16a6f97ffd07199e8a05efbef103793")), "&6Hegemony Artifact", "&7Doubles the stats of the reforge ", "&7on this item.", " ", "&8Grants immunity to the &0Wither 78effect.", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");
    public static ItemStack HEGEMONY_ARTIFACT = GUIHelper.addLore(GUIHelper.addSkull(Utils.urlToBase64("")), "&6Hegemony Artifact", "&7Doubles the stats of the reforge ", "&7on this item.", " ", "&8This item can be reforged!", "&6&lLEGENDARY ACCESSORY");

    // NEW ACCESSORIES
    public static ItemStack RESISTANT_SCALE = GUIHelper.addLore(new ItemStack(Material.PRISMARINE_SHARD), "&9Resistant Scale", "&7Defense: &a+30", " ", "", "&8This item can be reforged!", "&9&lRARE ACCESSORY");
    public static ItemStack YOUNG_BONE = GUIHelper.addLore(new ItemStack(Material.BONE), "&5Young Bone", "&7Speed: &a+5", " ", "", "&8This item can be reforged!", "&5&lEPIC ACCESSORY");

}