name: SkyblockRemastered
version: @version@
main: xyz.apollo30.skyblockremastered.SkyblockRemastered
load: STARTUP

commands:
  skyblockremastered:
    description: SkyblockRemasted Main Command
    aliases: [sr]
  gamemode:
    description: Change a players gamemode.
    permissions:
      sbr.gamemode:
        description: Changes the player's gamemode
        default: false
    aliases: [survival, creative, adventure, spectator, spec, gms, gmc, gma, gmsp, esurvival, ecreative, eadventure, espectator, espec]
  visit:
    description: Visit a player's island
    aliases: [lookup, view]
  hub:
    description: Warps you to the Skyblock Hub
  island:
    description: Teleports you to your private island
    aliases: [is]
  build:
    description: Allows the people with sbr.buildbypass to build
    permissions:
      sbr.buildbypass:
        description: Allows the player to bypass build.
    aliases: [bypass, buildbypass, bb]